### ISSUE TITLE
UX improvements for settings

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#163]
Hey, I'm just gonna keep posting issues for stuff I notice during trailing this, hope that's okay :)

In the page settings (and the branch settings) I was confused a couple of times why my changes did not persist, because I was not expecting the save button to be at the top of the page (out of the screen when scrolled down). I'd recommend either using save buttons for sections, or having a global save button at the bottom. If you're looking for inspiration, [this UI is pretty similar to what you are doing](https://www.youtube.com/watch?v=ZT4WRRhacWk)

**Comment by gempain** [comment]
> Hey, I'm just gonna keep posting issues for stuff I notice during trailing this, hope that's okay :)

@queicherius this is perfectly okay, and exactly what we expect from our community ! FYI I am working full time on this project, so I'm always looking out for new issues, also, see [this](https://github.com/getmeli/meli/issues/166) which I just created and think we should work on.

> In the page settings (and the branch settings) I was confused a couple of times why my changes did not persist, because I was not expecting the save button to be at the top of the page (out of the screen when scrolled down). I'd recommend either using save buttons for sections, or having a global save button at the bottom. If you're looking for inspiration, [this UI is pretty similar to what you are doing](https://www.youtube.com/watch?v=ZT4WRRhacWk)

Yes, this one has been haunting me for a while. I just didn't find inspiration. You didn't mention it, but there's also a UX issue when I added site-wide passwords... don't know if you noticed, but in the site settings, you need to save the form for all fields EXCEPT for the site password. It's odd, I know. Your suggestion is great ! We should either have sections with a separate save button, or one save button at the bottom. Considering what I just said about site passwords, some parts of the form might save separately, so having sections makes sense IMO. Thanks for providing some inspiration, I'll have a look.

**Comment by gempain** [comment]
This was released in v1.0.0-beta.7, we can reopen if further changes are needed. Thanks again for your help !

Side node, i've moved the site-password protection toggle in its own tab as it was weird to have the save button controlling only one part of the page. Hope this is something you expected.
