### ISSUE TITLE
UX improvements for toggle buttons

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#164]
I got confused a couple of times by the "off" state of the toggle button, since it still incorporates the brand color. Instead of having the gradiant background, I'd recommend just a plain dark gray, like this: ![](https://i.imgur.com/vpYg837.png)

**Comment by gempain** [comment]
Interesting ! What I'm concerned about in the example you provided is that it looks like it's in a **disabled** state, don't you think ?

**Comment by queicherius** [comment]
Personally, I don't think so - using gray for a non-active toggle feels pretty established. Here's an example from the [Anvil](https://anvil.servicetitan.com/components/form/toggle-switch/) design system and [Material Design](https://material.io/components/switches#usage)

**Comment by gempain** [comment]
Sounds good, I'll plan these changes for the next release.

**Comment by gempain** [comment]
I've made the changes, their already available on the `next` tag but I'll release tomorrow with a few other things. These are changes in the UI git repo, that's why GH is not picking them up.

**Comment by gempain** [comment]
This was released in v1.0.0-beta.7, we can reopen if further changes are needed. Thanks again for your help !
