### ISSUE TITLE
docs: improve docs for non docker-friendly users

### ISSUE THREAD

**Issue by gempain** [getmeli/meli#169]
See #168 for background.

Alongside the current installation [docs](https://github.com/getmeli/meli-docs), provide a step-by-step guide for installing Meli for users that are not familiar with Docker.

**Comment by gempain** [comment]
@raphaelparent to keep you updated, I have updated our readme (see [here](https://github.com/getmeli/meli/blob/next/README.md)) and updated our [installation docs](http://localhost:8000/get-started/installation/).

There are few things I can't include at the moment like how to setup your own VPS and more, I think there is great material out there to do this, and I feel like this should be done through a blog post. We are planning to start a blog with tutorials, so stay tuned !

Are the updates helpful ?

**Comment by raphaelparent** [comment]
@gempain yes they are! Thanks a lot! I'll start learning docker and I will eventually set up Meli. I'll keep you posted if I encounter any problems.

**Comment by gempain** [comment]
Hey @raphaelparent thanks for your reply ! I'll close this issue, but you sure should join us on our community channel. Stay tuned at #166.
