### ISSUE TITLE
Document how to use Meli behind a reverse proxy

### ISSUE THREAD

**Issue by gempain** [getmeli/meli#175]
See background here [here](https://github.com/getmeli/meli/issues/162#issuecomment-751875411).

@ayush123460 you're in control 🚀

**Comment by ayush123460** [comment]
Hey! Should I make a PR for the readme or in the docs directly? Can do either :D

**Comment by gempain** [comment]
The docs would be more than perfect, here's what I think we could do:
- you create a new page with instructions for installing behind a reverse proxy, details about your installation with Nginx, the command you mentioned, and anything you think is valuable
- I will re-organize the installation docs to guide users to the type of installation

I'll create an issue there, might be better than here. Managing multiple repos is tough, Github should have a way to reference repo-to-repo issues or have organization-level issues. But that's another story.

**Comment by ayush123460** [comment]
On it!

**Comment by ayush123460** [comment]
Hey! Found some time and decided to write the doc, PR [here](https://github.com/getmeli/meli-docs/pull/7). Let me know if there's any changes needed.

Edit: looks like your CI job for docs doesn't have a valid token

**Comment by gempain** [comment]
@ayush123460 hi there ! Thanks so much for helping out here ! I've been off the grid for a couple of days but I'll take a look tomorrow. Happy holidays !

Thanks to you I just learned you can reference issues and PRs in other repos by using <org>/<repo>#<id> 😀

**Comment by gempain** [comment]
This was merged, thanks again for your help !
