### ISSUE TITLE
npx command fails when executed via Github Actions

### ISSUE THREAD

**Issue by FritzerMcQ** [getmeli/meli#192]
Hi,
I set up a github action that will trigger a build process and publishes the build on my meli installation.
Whoever using the npx command:
`npx @getmeli/cli upload ./build --branch [branch] --site [site] --url [url] "--token=***"`

Will result in an npm error: 
`Cannot open assembly 'upload': No such file or directory.
npm ERR! code ELIFECYCLE
npm ERR! errno 2`

I wrapped that command as a npm script and tested the whole process on my computer. It went through without a problem. But fails when executed in github actions.
How the runner calls the command up above:
``` 
     - name: Run build & deploy
       working-directory: ./landingpage
       run: |
         npm ci
         npm run build
         npm run meli -- --token=${{secrets.MELI_TOKEN}}
```

I neither found any hint solving the problem on the web nor in an old issue here.
Thanks for helping

**Comment by pimartin** [comment]
Hi @FritzerMcQ,

I suspect it might be the [same issue as encountered by some people with the `@angular/cli`](https://gitter.im/Angular-Karma-Test-Explorer/Bugs?at=5d9e2a1a940b4c2fc0a3bdb6).

Could you please try the following command?
```shell
npx -p @getmeli/cli meli upload ...
```

And if it's still not enough:
```shell
npx -p "@getmeli/cli" meli upload ...
```

I'll investigate further if this doesn't solve your problem.

**Edit:** (fixed the commands above and:)
Could you also try to force npx to use the latest version of the cli (just in case)?
```shell
npx @getmeli/cli@latest upload ...
```

**Comment by FritzerMcQ** [comment]
Yes!
```
npx -p "@getmeli/cli" meli upload ...
```
this one worked fine.

Thank you!
