### ISSUE TITLE
Ability to set cache-control headers and compression

### ISSUE THREAD

**Issue by tanc** [getmeli/meli#195]
At the moment it seems like there is no cache-control header set and the resources are served with no compression (gzip, brotli).

It would be great if Meli had some sane defaults, much like Netlify does, which would make serving static files even more efficient. Then ideally there would be some settings to configure cache headers on a site-by-site basis within the UI (or a config file like Netlify uses).

Netlify set a cache-control header like this:
```
cache-control: public, max-age=0, must-revalidate
```
They say that it makes the browser re-check for changes each time but against the etag to see if anything has changed. Supposedly this is very efficient with HTTP2. From what I can tell without a cache-control header my browser is caching the resources served by Meli and when I update the branch with a new release I got inconsistent results. One time I reloaded the page and the css file I'd changed didn't update, then on other releases it did update. Without further testing its hard to say whether setting a cache-control would provide the consistency or hurt performance.

It would be good to see resources gzipped on-the-fly with Caddy, I believe this is the directive: https://caddyserver.com/docs/caddyfile/directives/encode

Thanks for your efforts!

**Comment by gempain** [comment]
@tanc thanks for the detailed request ! I think it's a great suggestion, we'll add this to the roadmap.

**Comment by gempain** [comment]
This is implemented in `next`. Cache headers are now set, and requests are gzipped. We've added the ability to define custom headers at the site level and at per branch. Branch headers will override site headers, and custom headers will override default headers configured by Meli (at the moment, cache control).

**Comment by tanc** [comment]
Wow amazing! Will test this out soon

**Comment by gempain** [comment]
This was released on beta. I'm closing, but feel free to comment and we'll reopen if needed.
