### ISSUE TITLE
[Feature Request] Email Static Form Submissions

### ISSUE THREAD

**Issue by tomershvueli** [getmeli/meli#201]
It'd be cool if Meli was able to parse through HTML sites for `<form>`'s and plug it into its backend to automatically email form responses to a site's admin. This would bring it to parity with [Netlify Forms](https://docs.netlify.com/forms/setup/).

**Comment by gempain** [comment]
@tomershvueli I'm happy to see someone asking this 😀  Spoiler alert, this is in the pipeline and we're working on it 🚀

**Comment by tomershvueli** [comment]
Great news!

**Comment by gempain** [comment]
@tomershvueli This will actually be available in 1.0.0-beta.20, had to re-release. We've updated the docs for [forms](https://docs.meli.sh/get-started/forms). Let us know what you think ! I'm sure there will be improvements, but this is a good start. Files are sent as attachments. In the future, we might add an in-memory forms and other integrations.

**Comment by gempain** [comment]
I'm closing, but you can keep commenting and we'll reopen if needed.

**Comment by tomershvueli** [comment]
This is awesome, thanks for the great work on this!
