### ISSUE TITLE
Feature-Reqeuest: Add Domain & ENV Bash

### ISSUE THREAD

**Issue by Berndinox** [getmeli/meli#210]
I would suggest to add those 2 features:

**1)**
Right now, you can just add an Domain with ACME or with a Custom Certificate.
When beeing behind an SSL-Terminating Reverse-Proxy (like in K8s) no Cert is needed at all.
How to solve: 3rd Option: Add Domain without Cert
![image](https://user-images.githubusercontent.com/1122698/111793282-66d37100-88c5-11eb-8611-89e864934fa6.png)

**2)**
MELI_MONGO_URI should be generated using a bash script inside the container.

In addition we should use the ENV VARs, eg.:

MELI_MONGO_USER
MELI_MONGO_PASSWORD
MELI_MONGO_HOST
MELI_MONGO_PORT
MELI_MONGO_DB

The second change is not mandatory, but would make the K8s config easier, also a Secret could be used to inject the Password.

**Comment by gempain** [comment]
1. When you set [`MELI_HTTPS_AUTO`](https://docs.meli.sh/environment-reference/server#meli_https_auto), Meli doesn't configure HTTPS at all, even though the UI makes it look like it. This may be confusing. Or are you having an issue getting the site ?
2. It makes sense. We're so used to only setting the URI that we've never really thought of this.

**Comment by Berndinox** [comment]
1. Yes, i have no issue, all working fine. It just was a bit confusing to me.
Some Users may not know about the HTTP_Auto "off" thing.

2. Yeah!, absolutely. Its more of a cosmetic ting. :)

**Comment by gempain** [comment]
2. Let's allow both, so everyone is happy.

**Comment by gempain** [comment]
This will be included in the next release.

I'm closing, but you can keep commenting and we'll reopen if needed.
