### ISSUE TITLE
Enable caddy option "hash_cache" for password protected pages

### ISSUE THREAD

**Issue by FloDwld** [getmeli/meli#222]
Hi! 
I noticed that enabling password protection for a page increases its load time by a factor of ~10x on my low-specced VPS. The reason seems to be that caddy has to do an expensive hash computation ([see the corresponding issue](https://github.com/caddyserver/caddy/issues/3462)) for every request on the page.

To fix that, they implemented the [hash_cache](https://caddyserver.com/docs/modules/http.authentication.providers.http_basic#hash_cache) option. I suggest enabling this option for all password protected pages to improve their load time. (There seems to be a tradeoff that passwords stay in memory for longer, but this tradeoff seems more than worth it to me)

Thanks!
Florian

**Comment by pimartin** [comment]
Hi, thank you for the suggestion.

This seems like a good idea, we'll add this soon.

**Comment by gempain** [comment]
This has been released on `next`. Should join `beta` tomorrow.

**Comment by FloDwld** [comment]
Thanks! I've given it a try on `next` and it really improves load times for consecutive requests to password protected pages for me.

**Comment by gempain** [comment]
Glad to know this helped ! It's now been released in `beta`, so I'll close, but feel free to comment and we'll reopen if needed.
