### ISSUE TITLE
Any way to upload branches/sites with API key (instead of token) via CLI or API?

### ISSUE THREAD

**Issue by joelr45** [getmeli/meli#241]
Just ran across meli, it seems to have a ton of awesome features!

I was just looking into the docs for the API and CLI and was just wondering if there is a way to upload a site or branch with the API key or via CLI with API key instead of the site ID and token? 

I am wondering for automation reasons. 

Thanks

**Comment by joelr45** [comment]
Nevermind, found the token handler!

**Comment by gempain** [comment]
Hi there, thanks for the kind words. I'm glad you sorted things out, you were ahead of me on this one.

Happy coding !
