### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by mtiller** [getmeli/meli#242]
I attempted to create a `helm` chart wrapping Mongo and Meli.  The Pods come up just fine and the ingresses and services all seem properly configured but I don't understand how things should map.  I don't need SSL, so I'm only targeting ports 80, 2019 and 3001.  But what I don't understand is if I intend to run this on `sites.example.org`, how should this all be routed?  What should `sites.example.org` route to? (which port, do I need to rewrite the `HOST` header?)

What should `<something>.sites.example.org` route to? (again, which port, etc)

I looked in `deployment/k8s` at the Kubernetes manifest there.  But there is no Ingress definition there, which leaves me guessing.

My guess is that `sites.examples.org` should route to port 80 and keep the `Host` header of `sites.examples.org` and that `my-site.sites.examples.org` should route to port 80 and keep the `Host` header of `my-site.sites.examples.org`.  But what about ports 2019 and 3001?  Do they need to be exposed via the `Ingress`?  Does the client assume those ports or does it assume they get remapped somehow?  Or are ports 2019 and 3001 only used internally with no need for an Ingress?

Thanks

**Comment by gempain** [comment]
@mtiller hi ! Your first guess is the right one: you should be using port 80, which is the only one exposed by our Docker image. Port 2019 is for Caddy's API and 3000 (not sure it's 3001) is for the Nodejs backend, but those are internal to the container.

**Comment by mtiller** [comment]
Everything seems to be working with my `helm` configuration.  Thanks.
