### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by mtiller** [getmeli/meli#246]
I see that there is a Kubernetes manifest provided for Meli, but no `helm` chart.  Helm is a little bit more convenient and makes customization a bit easer (_via_ the `values.yaml` file).  Are there any plans to provide an official `helm` chart?  I could contribute mine if anybody is interested.  I don't claim it is perfect, but as I mention in #233, it does provide a way of handling branches with SSL (if you are using `cert-manager`).

**Comment by titansmc** [comment]
I would be happy to see your helm chart if you don't mind.

**Comment by mtiller** [comment]
Happy to share it.  I need to do a bit more work to make it generic.  At a minimum, I guess I can submit a PR and you'll be able to see it there.  I'd just like to know that the PR has some chance of getting accepted.  But since you are interested, I'll go ahead and do it and hopefully it will get included.  Ideally, it would be good if it got published in a chart registry somewhere as well.

**Comment by titansmc** [comment]
I have asked in the discord group about the project and the developer mentioned that they don't have time to continue with the project anymore....I hope this is not the case!

**Comment by gempain** [comment]
@mtiller I have to admit my knowledge of helm and kubernetes varies from very limited to non existent. I'd be happy to accept a PR for this thought I have no real way to verify it except than making sure it works for your guys.

Regarding the fact that we don't have time anymore, my colleague @pimartin replied on Discord but I wanted to clarify things. I know you have offered to pay for support, and while this is a really awesome proposition, it's financially difficult to work on this project a lot when very few users are paying for it, and the day we accept paid support, we'll have to be there no matter what as we'll be contractually tied, while free usage gives us the freedom to develop when we can. We both have a full time job, and lots of things to work on, so finding time for Meli is hard. I look at issues and try to respond promptly but it's not always easy. That said, I'm happy to see contributions though. We're here to assist, but I'd love to see the community get involved more. It's easy to ask for features and open issues but we work on this in our free time and Meli is free of charge. We have the same problem as any open source software on Github: most people use it for free and want features while no one really wants to contribute or pay (I know @titansmc it's not your case).

**Comment by mtiller** [comment]
@gempain as I told @titansmc, I'll create a PR and you can choose to accept it or not.  Worst case, it just sits in a PR.

I think you are confusing me with someone else though.  I'm not on Discord and never made any mention about support.  I totally understand this is open source which is why in all my issues (except 1 I think), I offered to submit a pull request.  I'm happy to make the contribution.  My only concern is when those requests will ultimately find their way into the "official" Docker image.  I can easily build the images myself and deploy them in my own container registry, so it isn't a huge problem though.

**Comment by gempain** [comment]
Not you @mtiller, but @titansmc did say he asked us on Discord, and we had a user on Discord ask whether the project was still alive and mentioning he was willing to pay for support, to which my colleague @pimartin responded that we were a bit busy elsewhere for the moment. 

@mtiller you're actually one of the top contributors in terms of PRs and issues now: cross checking and responding to multiple issues, it's really awesome, thanks so much for this.

Also note that i'm super happy to accept PRs 😄

**Comment by mtiller** [comment]
OK, I submitted a PR.  So @titansmc, let me know if you have any issues.  I did a basic install myself and it worked.  I fully admit we could add more "knobs" to it and somebody else may very well need to in order for it to fit into their conventions/infrastructure/process.

I'll close this since I'm not expecting anybody else to do anything here.
