### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by GQAdonis** [getmeli/meli#257]
Is there active development going on in this project?

**Comment by gempain** [comment]
Hi there and thank you for asking. Dead is a bit of a strong word as we currently have hundreds of installations running everywhere in the cloud. The project is not actively maintained as free time is hard to find when you have got a busy life. The community is also welcome to participate, make pull requests etc. Meli works fine as it is and we there's always room for improvement. You are free to use it and if it fits your needs we'll be glad that we built something that helps you out. If it doesn't I'm sure there will be plenty of other tools out there to fit your needs.
