### ISSUE TITLE
Is document site down ?

### ISSUE THREAD

**Issue by magcho** [getmeli/meli#261]
I can not access meli document site (https://docs.meli.sh/)

I can't lookup the  A-record
```
$ dig a docs.meli.sh

; <<>> DiG 9.10.6 <<>> a docs.meli.sh
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 20920
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;docs.meli.sh.                  IN      A

;; AUTHORITY SECTION:
sh.                     3600    IN      SOA     a0.nic.sh. hostmaster.donuts.email. 1673232342 7200 900 1209600 3600

;; Query time: 282 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Jan 09 11:57:19 JST 2023
;; MSG SIZE  rcvd: 107
```

**Comment by kohenkatz** [comment]
It looks like the domain has now been taken over by advertising squatters.

**Comment by gempain** [comment]
Hi there 👋 
Sorry about this, I have just deployed the docs [here](https://docs.meli.charlie-bravo.be/).
The domain has not been renewed and seems to have been bought by, as you rightly say, ad scammers...
I have already made the changes in our readmes but I will be making a new beta release with updated links in the coming days 😄
