### ISSUE TITLE
Add the ability to set a site-wide password

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#7]
I would like to set a password on a site basis, so it gets automatically applied to all branches that get uploaded.

The use-case here is an internal documentation I would like to deploy once for master, and then automatically for each pull request - but all branches have to be protected.

An alternative would be the ability to set the password via the CLI tool during upload.

**Comment by gempain** [comment]
Hi @queicherius, and thanks for open an issue here. It's a great idea, and I'll add this to the next release.

> An alternative would be the ability to set the password via the CLI tool during upload.

It makes sense, but in the context of CI, I think this would be difficult to use unless you have a manual job for setting it. I'd like to keep the CLI dedicated to uploading releases at the moment, but I'll keep this in mind anyway.

I'll work on this and add it to the next release.

**Comment by gempain** [comment]
@queicherius this fix was released in v1.0.0-beta.5. A toggle is now available in your site settings. It's the same toggle and behavior as for site branches. I'm closing, but you may continue to reply if further help is required. We'll reopen if needed. Again, many thanks for contributing to this project.

Note that if you set a site-wide password and then a branch password, the branch password will override the site's password.

**Comment by queicherius** [comment]
Awesome, thank you so much!

**Comment by gempain** [comment]
Very welcome 🙇‍♀️
